// Generated from config/routes.json by tools/pio_embed_assets.py.
// Do not edit this file directly.
#ifndef SMARTCOOLING_ROUTES_H
#define SMARTCOOLING_ROUTES_H

static constexpr const char *ROUTE_CONFIG = "/u4CwT7";
static constexpr const char *ROUTE_DEVICE = "/m2VhK9";
static constexpr const char *ROUTE_EVENTS = "/t9BaN2";
static constexpr const char *ROUTE_LOGIN = "/A7xQm2";
static constexpr const char *ROUTE_OTA = "/K4qWs7";
static constexpr const char *ROUTE_PASSWORD = "/Pq3Rz8";
static constexpr const char *ROUTE_PREVIEW = "/R6sJq1";
static constexpr const char *ROUTE_REBOOT = "/N8jDv5";
static constexpr const char *ROUTE_RECOVER = "/g9LzT4";
static constexpr const char *ROUTE_RGB = "/H3vXk6";
static constexpr const char *ROUTE_SAVE = "/d5YpM8";
static constexpr const char *ROUTE_STATUS = "/Z8nLp3";
static constexpr const char *ROUTE_WS = "/x2FzQ9";

#endif
