import json
import re
from pathlib import Path

try:
    Import("env")
    project_dir = Path(env.subst("$PROJECT_DIR"))
except NameError:
    project_dir = Path(__file__).resolve().parents[1]

source_path = project_dir / "web" / "index.html"
routes_path = project_dir / "config" / "routes.json"
component_include_path = project_dir / "components" / "smartcooling" / "include"
web_target_path = component_include_path / "web_assets.h"
routes_target_path = component_include_path / "routes.h"
delimiter = "EWPHTML"

if not source_path.is_file():
    raise FileNotFoundError(f"WebApp source not found: {source_path}")
if not routes_path.is_file():
    raise FileNotFoundError(f"Route map not found: {routes_path}")

routes = json.loads(routes_path.read_text(encoding="utf-8"))
required_routes = {
    "login", "recover", "password", "device", "status", "config", "preview",
    "save", "rgb", "events", "ota", "ws", "reboot",
}
missing_routes = sorted(required_routes - set(routes))
if missing_routes:
    raise ValueError(f"config/routes.json missing routes: {', '.join(missing_routes)}")

seen_paths = set()
for name, path in routes.items():
    if not re.fullmatch(r"/[A-Za-z0-9]{6}", path):
        raise ValueError(f"Route {name} must look like /A1bC2d")
    if path in seen_paths:
        raise ValueError(f"Duplicate route path: {path}")
    seen_paths.add(path)

routes_json = json.dumps(routes, separators=(",", ":"), sort_keys=True)
html = source_path.read_text(encoding="utf-8").replace("__SMARTCOOLING_ROUTES__", routes_json)
if "__SMARTCOOLING_ROUTES__" in html:
    raise ValueError("Route token replacement failed")

closing_token = f'){delimiter}\"'
if closing_token in html:
    raise ValueError(f"Index.html contains reserved raw-string token: {closing_token}")

web_generated = f'''// Generated from web/index.html by tools/pio_embed_assets.py.
// Do not edit this file directly.
#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <Arduino.h>

static const char index_html[] PROGMEM = R"{delimiter}(
{html}
){delimiter}";

#endif
'''

route_lines = [
    "// Generated from config/routes.json by tools/pio_embed_assets.py.",
    "// Do not edit this file directly.",
    "#ifndef SMARTCOOLING_ROUTES_H",
    "#define SMARTCOOLING_ROUTES_H",
    "",
]
for name in sorted(routes):
    route_lines.append(f'static constexpr const char *ROUTE_{name.upper()} = "{routes[name]}";')
route_lines += ["", "#endif", ""]
routes_generated = "\n".join(route_lines)

web_target_path.parent.mkdir(parents=True, exist_ok=True)
if not web_target_path.exists() or web_target_path.read_text(encoding="utf-8") != web_generated:
    web_target_path.write_text(web_generated, encoding="utf-8", newline="\n")
    print(f"Embedded {len(html.encode('utf-8'))} bytes from web/index.html")

if not routes_target_path.exists() or routes_target_path.read_text(encoding="utf-8") != routes_generated:
    routes_target_path.write_text(routes_generated, encoding="utf-8", newline="\n")
    print(f"Generated route header from config/routes.json")
